/*
 @overview es6-promise - a tiny implementation of Promises/A+.
 @copyright Copyright (c) 2014 Yehuda Katz, Tom Dale, Stefan Penner and contributors (Conversion to ES6 API by Jake Archibald)
 @license   Licensed under MIT license
            See https://raw.githubusercontent.com/stefanpenner/es6-promise/master/LICENSE
 @version   4.1.0+f046478d
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(y){var n=0;return function(){return n<y.length?{done:!1,value:y[n++]}:{done:!0}}};$jscomp.arrayIterator=function(y){return{next:$jscomp.arrayIteratorImpl(y)}};$jscomp.makeIterator=function(y){var n="undefined"!=typeof Symbol&&Symbol.iterator&&y[Symbol.iterator];return n?n.call(y):$jscomp.arrayIterator(y)};
(function(y,n){"object"===typeof exports&&"undefined"!==typeof module?module.exports=n():"function"===typeof define&&define.amd?define(n):y.ES6Promise=n()})(this,function(){function y(){return function(){return process.nextTick(D)}}function n(){return"undefined"!==typeof W?function(){W(D)}:r()}function Q(){var d=0,h=new ca(D),l=document.createTextNode("");h.observe(l,{characterData:!0});return function(){l.data=d=++d%2}}function V(){var d=new MessageChannel;d.port1.onmessage=D;return function(){return d.port2.postMessage(0)}}
function r(){var d=setTimeout;return function(){return d(D,1)}}function D(){for(var d=0;d<M;d+=2)(0,a[d])(a[d+1]),a[d]=void 0,a[d+1]=void 0;M=0}function u(){try{var d=require("vertx");W=d.runOnLoop||d.runOnContext;return n()}catch(h){return r()}}function e(d,h){var l=arguments,p=this,w=new this.constructor(N);void 0===w[f]&&P(w);var z=p._state;z?function(){var K=l[z-1];R(function(){return I(z,w,K,p._result)})}():B(p,w,d,h);return w}function G(d){if(d&&"object"===typeof d&&d.constructor===this)return d;
var h=new this(N);A(h,d);return h}function N(){}function Z(d){try{return d.then}catch(h){return t.error=h,t}}function O(d,h,l,p){try{d.call(h,l,p)}catch(w){return w}}function X(d,h,l){R(function(p){var w=!1,z=O(l,h,function(K){w||(w=!0,h!==K?A(p,K):x(p,K))},function(K){w||(w=!0,q(p,K))},"Settle: "+(p._label||" unknown promise"));!w&&z&&(w=!0,q(p,z))},d)}function L(d,h){h._state===g?x(d,h._result):h._state===k?q(d,h._result):B(h,void 0,function(l){return A(d,l)},function(l){return q(d,l)})}function m(d,
h,l){h.constructor===d.constructor&&l===e&&h.constructor.resolve===G?L(d,h):l===t?(q(d,t.error),t.error=null):void 0===l?x(d,h):"function"===typeof l?X(d,h,l):x(d,h)}function A(d,h){if(d===h)q(d,new TypeError("You cannot resolve a promise with itself"));else{var l=typeof h;null===h||"object"!==l&&"function"!==l?x(d,h):m(d,h,Z(h))}}function v(d){d._onerror&&d._onerror(d._result);J(d)}function x(d,h){d._state===c&&(d._result=h,d._state=g,0!==d._subscribers.length&&R(J,d))}function q(d,h){d._state===
c&&(d._state=k,d._result=h,R(v,d))}function B(d,h,l,p){var w=d._subscribers,z=w.length;d._onerror=null;w[z]=h;w[z+g]=l;w[z+k]=p;0===z&&d._state&&R(J,d)}function J(d){var h=d._subscribers,l=d._state;if(0!==h.length){for(var p,w,z=d._result,K=0;K<h.length;K+=3)p=h[K],w=h[K+l],p?I(l,p,w,z):w(z);d._subscribers.length=0}}function C(){this.error=null}function I(d,h,l,p){var w="function"===typeof l,z=void 0,K=void 0,ea=void 0,fa=void 0;if(w){try{z=l(p)}catch(ha){da.error=ha,z=da}z===da?(fa=!0,K=z.error,
z.error=null):ea=!0;if(h===z){q(h,new TypeError("A promises callback cannot return that same promise."));return}}else z=p,ea=!0;h._state===c&&(w&&ea?A(h,z):fa?q(h,K):d===g?x(h,z):d===k&&q(h,z))}function F(d,h){try{h(function(l){A(d,l)},function(l){q(d,l)})}catch(l){q(d,l)}}function P(d){d[f]=aa++;d._state=void 0;d._result=void 0;d._subscribers=[]}function S(d,h){this._instanceConstructor=d;this.promise=new d(N);this.promise[f]||P(this.promise);ba(h)?(this._remaining=this.length=h.length,this._result=
Array(this.length),0===this.length?x(this.promise,this._result):(this.length=this.length||0,this._enumerate(h),0===this._remaining&&x(this.promise,this._result))):q(this.promise,Error("Array Methods must be provided an Array"))}function E(d){this[f]=aa++;this._result=this._state=void 0;this._subscribers=[];if(N!==d){if("function"!==typeof d)throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(this instanceof E)F(this,d);else throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");
}}var T=void 0,ba=T=Array.isArray?Array.isArray:function(d){return"[object Array]"===Object.prototype.toString.call(d)},M=0,W=void 0,Y=void 0,R=function(d,h){a[M]=d;a[M+1]=h;M+=2;2===M&&(Y?Y(D):b())},H=(T="undefined"!==typeof window?window:void 0)||{},ca=H.MutationObserver||H.WebKitMutationObserver;H="undefined"===typeof self&&"undefined"!==typeof process&&"[object process]"==={}.toString.call(process);var U="undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof importScripts&&"undefined"!==
typeof MessageChannel,a=Array(1E3),b=void 0;b=H?y():ca?Q():U?V():void 0===T&&"function"===typeof require?u():r();var f=Math.random().toString(36).substring(16),c=void 0,g=1,k=2,t=new C,da=new C,aa=0;S.prototype._enumerate=function(d){for(var h=0;this._state===c&&h<d.length;h++)this._eachEntry(d[h],h)};S.prototype._eachEntry=function(d,h){var l=this._instanceConstructor,p=l.resolve;p===G?(p=Z(d),p===e&&d._state!==c?this._settledAt(d._state,h,d._result):"function"!==typeof p?(this._remaining--,this._result[h]=
d):l===E?(l=new l(N),m(l,d,p),this._willSettleAt(l,h)):this._willSettleAt(new l(function(w){return w(d)}),h)):this._willSettleAt(p(d),h)};S.prototype._settledAt=function(d,h,l){var p=this.promise;p._state===c&&(this._remaining--,d===k?q(p,l):this._result[h]=l);0===this._remaining&&x(p,this._result)};S.prototype._willSettleAt=function(d,h){var l=this;B(d,void 0,function(p){return l._settledAt(g,h,p)},function(p){return l._settledAt(k,h,p)})};E.all=function(d){return(new S(this,d)).promise};E.race=
function(d){var h=this;return ba(d)?new h(function(l,p){for(var w=d.length,z=0;z<w;z++)h.resolve(d[z]).then(l,p)}):new h(function(l,p){return p(new TypeError("You must pass an array to race."))})};E.resolve=G;E.reject=function(d){var h=new this(N);q(h,d);return h};E._setScheduler=function(d){Y=d};E._setAsap=function(d){R=d};E._asap=R;E.prototype={constructor:E,then:e,"catch":function(d){return this.then(null,d)}};E.polyfill=function(){var d=void 0;if("undefined"!==typeof global)d=global;else if("undefined"!==
typeof self)d=self;else try{d=Function("return this")()}catch(p){throw Error("polyfill failed because global object is unavailable in this environment");}var h=d.Promise;if(h){var l=null;try{l=Object.prototype.toString.call(h.resolve())}catch(p){}if("[object Promise]"===l&&!h.cast)return}d.Promise=E};E.Promise=E;E.polyfill();return E});
var fcdsc=function(){function y(){return new Promise(function(a,b){e("trackVisit");if(U)e("DST not tracking because visitor has opted out of tracking, exiting.");else{var f=new V;f.load(window.location.href);var c=m("_fcdscv");if(!f.hasUtmData()){if(c){e("No UTM data in URL and cookie exists, exiting.");return}f.UtmSource="internal"}var g=new D;c?(g.load(c),g.addVisit(f),g.save().then(function(k){e("Success! "+k.Message);g.resetAndSaveToCookie();a(k.Message)},function(k){e("Failed!",k);b(k)})):(e("getVisitorId"),
L("https://st.fullcircleinsights.com/v1/visitors/create",JSON.stringify({CustomerId:"b846fedf-4f17-40c0-b71d-a717a6afd797"})).then(function(k){k=JSON.parse(k.Message);e("VisitorId:"+k.VisitorId);g.Visitor=new r(null,k.VisitorId);g.saveToCookie();g.addVisit(f);g.save().then(function(t){e("Success! "+t.Message);g.resetAndSaveToCookie();a(t.Message)},function(t){e("Failed!",t);b(t)})},function(k){console.error("Failed!",k);k="Error creating new visitor. "+k+" Response: "+Y+" Page: "+window.location.pathname;g.DiagnosticMessage=
k;e(k);N(g)}))}})}function n(a){return new Promise(function(b,f){e("m_trackFormFill");if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(a))if(U)e("DST not tracking because visitor has opted out of tracking, exiting.");else{var c=new D;if(q()){var g="trackFormFill cannot save because DoNotTrack is enabled";c.DiagnosticMessage=g;e(g);G(c,b,f)}else(g=m("_fcdscv"))?(c.load(g),c.Visitor.ExternalVisitorId?(c.Visitor=new r(a,c.Visitor.ExternalVisitorId),c.Activities.push(new u("Form",a)),e("m_trackFormFill::vi: "+c.toString()),
c.convert().then(function(k){e("m_trackFormFill::vi.convert response::"+k.Message);c.resetAndSaveToCookie();H="";b(k.Message)},function(k){e("m_trackFormFill::vi.convert error::",k);f(k)})):(g="trackFormFill cannot save because there is no visitor id",c.DiagnosticMessage=g,e(g),G(c,b,f))):(g="trackFormFill cannot save because cookie does not exist or value is blank. Page: "+window.location.pathname,c.DiagnosticMessage=g,e(g),G(c,b,f))}else e("Invalid email")})}function Q(a){if(!a)return!1;for(var b=
"auth0.com,community.auth0.com,support.auth0.com,marketplace.auth0.com,manage.auth0.com,jwt.io,samltool.io,webauthn.me,webtask.io,sharelock.io,openidconnect.net,identityunlocked.com,identityunlocked.auth0.com,squarezerocmx.com,auth0.org,avocadolabs.dev,info.auth0.com".toString().split(","),f=0;f<b.length;f++)if(a.includes(b[f]))return!0;return!1}function V(){this.SessionStartTime=this.ReferrerPageRaw=this.ReferrerPage=this.UtmContent=this.UtmTerm=this.UtmCampaign=this.UtmMedium=this.UtmSource=this.UrlRaw=this.UrlPath=this.Email=this.Origin=this.VisitDateTime=null;this.load=function(a){this.VisitDateTime=O(new Date);this.SessionStartTime=Z();this.UrlPath=encodeURIComponent(window.location.pathname);this.Origin=encodeURIComponent(window.location.hostname);
this.UrlRaw=encodeURIComponent(window.location);a=a.split("?");if(1<a.length){a=a[1].split("&");for(var b=0;b<a.length;b++){var f=a[b].split("=");"utm_source"==f[0]?this.UtmSource=f[1]:"utm_medium"==f[0]?this.UtmMedium=f[1]:"utm_campaign"==f[0]?this.UtmCampaign=f[1]:"utm_term"==f[0]?this.UtmTerm=f[1]:"utm_content"==f[0]&&(this.UtmContent=f[1])}}if(document.referrer){if(b=document.referrer,a=encodeURIComponent(b),this.ReferrerPageRaw=255<a.length?a.substring(0,255):a,a=document.createElement("a"),
a.href=b,a=a.hostname,f=encodeURIComponent(a),this.ReferrerPage=255<f.length?f.substring(0,255):f,!this.hasUtmData()){b=b.split("?");if(1<b.length)for(f=b[1].split("&"),b=0;b<f.length;b++){var c=f[b].split("=");if("q"==c[0]&&a.startsWith("www.bing.")){this.UtmTerm=c[1];break}}a.startsWith("www.bing.")?(this.UtmSource="bing",this.UtmMedium="organic"):a.startsWith("search.yahoo.")?(this.UtmSource="yahoo",this.UtmMedium="organic"):a.startsWith("www.google.")?(this.UtmSource="google",this.UtmMedium="organic"):
a.startsWith("www.facebook.")?(this.UtmSource="facebook",this.UtmMedium="social"):a.startsWith("www.linkedin.")||a.startsWith("www.lnkd.")?(this.UtmSource="linkedin",this.UtmMedium="social"):a.startsWith("www.twitter.")||a.startsWith("t.co")?(this.UtmSource="twitter",this.UtmMedium="social"):Q(a)||(this.UtmMedium="referral")}}else this.hasUtmData()||(this.UtmSource="direct")};this.loadFromJSON=function(a){this.VisitDateTime=a.VisitDateTime;this.UrlPath=a.UrlPath;this.Origin=a.Origin;this.UrlRaw=a.UrlRaw;
this.Email=a.Email;this.UtmSource=a.UtmSource;this.UtmMedium=a.UtmMedium;this.UtmCampaign=a.UtmCampaign;this.UtmTerm=a.UtmTerm;this.UtmContent=a.UtmContent;this.ReferrerPage=a.ReferrerPage;this.ReferrerPageRaw=a.ReferrerPageRaw};this.equals=function(a){return this.UtmSource==a.UtmSource&&this.UtmMedium==a.UtmMedium&&this.UtmCampaign==a.UtmCampaign&&this.UtmTerm==a.UtmTerm&&this.UtmContent==a.UtmContent};this.hasUtmData=function(){return null!==this.UtmSource||null!==this.UtmMedium||null!==this.UtmCampaign||
null!==this.UtmTerm||null!==this.UtmContent}}function r(a,b){this.Email=a;this.ExternalVisitorId=b}function D(){this.CustomerId="b846fedf-4f17-40c0-b71d-a717a6afd797";this.Visitor=null;this.Visits=[];this.Activities=[];this.DiagnosticMessage=null;this.load=function(a){a=JSON.parse(a);this.CustomerId=a.CustomerId;this.Visitor=a.Visitor;this.Activities=a.Activities;this.DiagnosticMessage=a.DiagnosticMessage;for(var b=0;b<a.Visits.length;b++){var f=new V;f.loadFromJSON(a.Visits[b]);this.Visits.push(f)}};this.addActivity=
function(a){this.Activities.push(a)};this.addVisit=function(a){if(0!==this.Visits.length)for(var b=0;b<this.Visits.length;b++)if(this.Visits[b].equals(a))return;this.Visits.push(a)};this.save=function(){return L("https://st.fullcircleinsights.com/v1/visits/queue",JSON.stringify(this))};this.convert=function(){return L("https://st.fullcircleinsights.com/v1/visits/convert",JSON.stringify(this))};this.toString=function(){return JSON.stringify(this)};this.encode=function(){return window.btoa(this.toString())};this.saveToCookie=
function(){e("VisitInfo::saveToCookie");var a=this.toString();v("_fcdscv",a,730);e("VisitInfo::saveToCookie::vi: "+a)};this.reset=function(){e("VisitInfo::reset");this.Visits=[];this.Activities=[]};this.resetAndSaveToCookie=function(){e("VisitInfo::resetAndSaveToCookie");this.Visits=[];this.Activities=[];this.saveToCookie()};this.updateVisitsAfterForm=function(a){e("VisitInfo::updateVisitsAfterForm");0!==this.Visits.length&&(this.Visits[this.Visits.length-1].Email=a)}}function u(a,b){this.ActivityDateTime=
O(new Date);this.Type=a;this.UrlPath=encodeURIComponent(window.location.pathname);this.Email=b}function e(a){T&&console.log("FCDSC v1.0.56("+window.location.hostname+"): "+a)}function G(a,b,f){a.save().then(function(c){e("sendDiagnostic::vi.save response::"+c.Message);b(c.Message)},function(c){e("sendDiagnostic::vi.save error::",c);f(c)})}function N(a){a.save().then(function(b){e("sendDiagnostic::vi.save response::"+b.Message)},function(b){e("sendDiagnostic::vi.save error::",b)})}function Z(){e("getSessionStartTime");
var a=A("_fcdscst");if(!a)return e("Visit::getSessionStartTime: session cookie not found, using current date/time for SessionStartTime"),O(new Date);a=new Date(parseInt(a));return isNaN(a.getUTCFullYear())?(e("Visit::getSessionStartTime: invalid value found in session cookie, using current date/time for SessionStartTime"),O(new Date)):O(a)}function O(a){var b=a.getUTCFullYear().toString()+"-",f=(a.getUTCMonth()+1).toString();1==f.length&&(f="0"+f);var c=a.getUTCDate().toString();1==c.length&&(c="0"+
c);var g=a.getUTCHours().toString();1==g.length&&(g="0"+g);var k=a.getUTCMinutes().toString();1==k.length&&(k="0"+k);a=a.getUTCSeconds().toString();1==a.length&&(a="0"+a);return b+(f+"-"+c+" "+g+":"+k+":"+a)}function X(a,b){return new Promise(function(f,c){function g(){var t=new XMLHttpRequest;t.open("POST",a);t.setRequestHeader("x-api-key","tUFsJqwVFG7n5OF2yvslKadj97U0d41iaVbDmDDd");t.setRequestHeader("origin-fci",window.location.origin);t.setRequestHeader("js-version","1.0.56");t.onload=function(){e("post::Status: "+
t.status);200==t.status?""==t.response||"undefined"===typeof t.response?c(Error("Empty response. User agent: "+navigator.userAgent)):f(t.response):c(Error(t.statusText))};t.onerror=function(){5>k?(k++,g()):(Y=t.response,c(Error("Network errors. Origin: "+self.origin+" User agent: "+navigator.userAgent)))};t.send(b)}e("post");var k=0;g()})}function L(a,b){return X(a,b).then(function(f){Y=f;return JSON.parse(f)})}function m(a){a+="=";for(var b=decodeURIComponent(document.cookie).split(";"),f=0;f<b.length;f++){for(var c=
b[f];" "==c.charAt(0);)c=c.substring(1);if(0===c.indexOf(a))return window.atob(c.substring(a.length,c.length))}return""}function A(a){a+="=";for(var b=decodeURIComponent(document.cookie).split(";"),f=0;f<b.length;f++){for(var c=b[f];" "==c.charAt(0);)c=c.substring(1);if(0===c.indexOf(a)){a=c.substring(a.length,c.length);try{return a=window.atob(a)}catch(g){return a}}}return""}function v(a,b,f){var c=new Date;c.setTime(c.getTime()+864E5*f);f="expires="+c.toUTCString();document.cookie=a+"="+window.btoa(b)+
";"+f+";domain=auth0.com;path=/;SameSite=Lax"}function x(a,b){document.cookie=a+"="+window.btoa(b)+";domain=auth0.com;path=/;SameSite=Lax"}function q(){if(!R||"false"==R)return!1;var a=window.doNotTrack||window.navigator.doNotTrack||window.navigator.msDoNotTrack;return a?"1"===a.charAt(0)||"yes"===a?(e("DoNotTrack is enabled, exiting"),!0):!1:!1}function B(){e("getForms");for(var a=document.getElementsByTagName("form"),b=0;b<a.length;b++){e("form: "+a[b].id);var f=!ca||
"false"==ca;if(a[b].classList&&a[b].classList.contains("fcidstform"))if(document.getElementById(M)&&a[b].contains(document.getElementById(M)))document.getElementById(M).addEventListener("change",fcdsc.handleEmailFieldChange);else if(0<a[b].getElementsByTagName("input").length&&a[b].getElementsByTagName("input")[M])a[b].getElementsByTagName("input")[M].addEventListener("change",fcdsc.handleEmailFieldChange);else for(var c=a[b].getElementsByTagName("input"),g=0;g<c.length;g++)if(c[g].type==M){c[g].value&&
(H=c[g].value);c[g].addEventListener("change",fcdsc.handleEmailFieldChange);break}("elq-form"===a[b].className||a[b].action&&"string"===typeof a[b].action&&a[b].action.includes("eloqua")||a[b].className.includes("eloqua-form")||a[b].className.includes("elq-form"))&&f&&(W=!1,a[b].addEventListener("submit",fcdsc.handleSubmit,!1));if("pardot-form"===a[b].id)for(g=0;g<a[b].childNodes.length;g++)if(a[b].childNodes[g].classList&&(a[b].childNodes[g].classList.contains("form-field")||a[b].childNodes[g].classList.contains("form-group"))&&
a[b].childNodes[g].classList.contains("email"))for(var k=0;k<a[b].childNodes[g].childNodes.length;k++)if("input"==a[b].childNodes[g].childNodes[k].nodeName.toLowerCase()){a[b].childNodes[g].childNodes[k].value&&f&&(H=a[b].childNodes[g].childNodes[k].value,a[b].addEventListener("submit",fcdsc.handleSubmit,!1));e("adding change event listener to email field id: "+a[b].childNodes[g].childNodes[k].id);a[b].childNodes[g].childNodes[k].addEventListener("change",fcdsc.handleEmailFieldChange);break}if("elq-form"===
a[b].className||a[b].action&&"string"===typeof a[b].action&&a[b].action.includes("eloqua")||a[b].className.includes("eloqua-form")||a[b].className.includes("elq-form"))for(c=a[b].getElementsByTagName("input"),g=0;g<c.length;g++)if("emailAddress"==c[g].name){c[g].value&&(H=c[g].value);e("adding change event listener to email field id: "+c[g].id);c[g].addEventListener("change",fcdsc.handleEmailFieldChange);break}if(a.item(b).classList&&(a.item(b).classList.contains("mktoForm")||a.item(b).classList.contains("marketo-form")||
a.item(b).classList.contains("marketo")))for(e("reached mktoForm block"),c=a[b].getElementsByTagName("input"),g=0;g<c.length;g++)if(c[g].id.startsWith("Email")||c[g].name.startsWith("Email")||c[g].classList&&c[g].classList.contains("mktoEmailField")){c[g].value&&(e("prefilledEmail: "+c[g].value),H=c[g].value);e("adding change event listener to Marketo email field");c[g].addEventListener("change",fcdsc.handleEmailFieldChange);break}if(a[b].id&&"string"===typeof a[b].id&&0===a[b].id.indexOf("gform"))for(c=
a[b].getElementsByTagName("input"),g=0;g<c.length;g++)c[g].parentElement.classList.contains("ginput_container_email")&&(c[g].value&&(H=c[g].value),e("adding change event listener to email field id: "+c[g].id),c[g].addEventListener("change",fcdsc.handleEmailFieldChange))}a=document.getElementsByClassName("pardot-form");for(b=0;b<a.length;b++){var t=a[b].getElementsByTagName("form");for(g=0;g<t.length;g++)for(c=t[g].getElementsByTagName("input"),k=0;k<c.length;k++)c[k].name.includes("email")&&(c[k].value&&
f&&(H=c[k].value,t[g].addEventListener("submit",fcdsc.handleSubmit,!1)),e("adding change event listener to Pardot email field"),c[k].addEventListener("change",fcdsc.handleEmailFieldChange))}f=document.getElementsByClassName("cta-form");for(b=0;b<f.length;b++)for(c=f[b].getElementsByTagName("form"),g=0;g<c.length;g++)if(k=c[g].querySelector("[data-mapping='email']"))k.value&&(H=k.value),e("adding change event listener to Uberflip email field"),k.addEventListener("change",fcdsc.handleEmailFieldChange)}
function J(a){e("m_handleSubmit");var b=null,f=a.currentTarget;try{a.preventDefault();e("form id: "+f.id);if(H)b=H;else{if("pardot-form"===f.id)for(var c=0;c<f.childNodes.length;c++)if(f.childNodes[c].classList&&f.childNodes[c].classList.contains("form-field")&&f.childNodes[c].classList.contains("email"))for(a=0;a<f.childNodes[c].childNodes.length;a++)if("input"==f.childNodes[c].childNodes[a].nodeName.toLowerCase()){var g=f.childNodes[c].childNodes[a].id;e("email field id: "+g);b=f.elements.namedItem(g).value;
break}if("elq-form"===f.className||f.action&&"string"===typeof f.action&&f.action.includes("eloqua")||f.className.includes("eloqua-form")||f.className.includes("elq-form")){var k=f.getElementsByTagName("input");for(c=0;c<k.length;c++)if("emailAddress"==k[c].name){e("email field id: "+k[c].id);b=k[c].value;break}}if(f.id&&"string"===typeof f.id&&0===f.id.indexOf("gform")){k=f.getElementsByTagName("input");for(c=0;c<k.length;c++)if(k[c].parentElement.classList.contains("ginput_container_email")){e("email field id: "+
k[c].id);e("email field value: "+k[c].value);b=k[c].value;break}if(b){setTimeout(function(){n(b)},500);f.submit();return}}f.classList.contains("fcidstform")&&document.getElementById("email")&&f.contains(document.getElementById("email"))&&(b=document.getElementById("email").value)}b?W?setTimeout(function(){n(b)},500):window==window.top?F(b):parent.postMessage('{ "sender" : "fcdsc", "type": "setuppendingsave", "email" : "'+b+'"}',"*"):e("could not find email field/value");f.submit()}catch(t){f.submit()}}
function C(a){e("m_handleSubmitHS");var b=null,f=null;a=a.target;for(var c=0;c<a.elements.length;c++)a.elements[c].name&&"email"===a.elements[c].name.toLowerCase()&&(b=a.elements[c].value),a.elements[c].name&&"hs_context"===a.elements[c].name.toLowerCase()&&(f=JSON.parse(a.elements[c].value));b?f?f.redirectUrl?F(b):setTimeout(function(){n(b)},500):e("could not find hs_context"):e("could not find email field/value")}function I(){e("m_checkForPendingSave");if(window==window.top){var a=m("_fcdsctmp");
e("email: "+a);a?(v("_fcdsctmp","",""),n(a)):e("email cookie _fcdsctmp not present, exiting")}else parent.postMessage('{ "sender" : "fcdsc", "type": "checkforpendingsave" }',"*")}function F(a){e("m_setupPendingSave");U?e("DST not tracking because visitor has opted out of tracking, exiting."):v("_fcdsctmp",a,1)}function P(a){e("m_setupPendingMultiSave");U?e("DST not tracking because visitor has opted out of tracking, exiting."):v("_fcdscms",a,1)}function S(a,b){try{e("m_handleSubmitMkto");if(!H)return e("prefilledEmail variable is blank, so trackFormFill must have already been called. Exiting"),
!0;e("values: "+JSON.stringify(a));e("followUpUrl: "+b);var f=H;a&&a.Email&&(f=a.Email);e("email: "+f);n(f).then(function(c){e("m_handleSubmitMkto success");return!0},function(c){e("m_handleSubmitMkto error");return!0})}catch(c){}return!0}function E(a){e("m_addMutationObservers");a&&"string"===typeof a&&(ba=a);if("NO_DYNAMIC_NODES"!==ba){var b=ba.toString().split(",");a=new MutationObserver(function(g){g=$jscomp.makeIterator(g);for(var k=g.next();!k.done;k=g.next())"childList"===k.value.type&&fcdsc.getForms()});
var f={attributes:!1,childList:!0,subtree:!0};if(0<b.length){var c=null;b=$jscomp.makeIterator(b);for(c=b.next();!c.done;c=b.next()){c=c.value;if("FCI-ALL"===c){document.body?(e("adding mutation observer to body"),a.observe(document.body,f)):e("cannot add mutation observer to body because it has not rendered yet");break}c=document.getElementById(c);null!=c&&a.observe(c,f)}}}}var T=false,ba="FCI-ALL",M="email",W=!0,Y="placeholder",R=true,
H="",ca=false,U=!1;return{init:function(){var a=void 0;a=window.location.href;var b="l".replace(/[\[\]]/g,"\\$&");b=(new RegExp("[?&]"+b+"(=([^&#]*)|&|#|$)")).exec(a);"fcidevqa"===(b?b[2]?decodeURIComponent(b[2].replace(/\+/g," ")):"":null)&&(T=!0);U||A("_fcdscblock")?(e("DST not tracking because visitor has opted out of tracking."),U=!0):(a=A("_fcdscst"),b=new Date,a?(a=new Date(parseInt(a)),a.setMinutes(a.getMinutes()+parseInt("60"))<
b&&x("_fcdscst",b.getTime().toString())):x("_fcdscst",b.getTime().toString()))},isValidOrigin:function(a){return Q(a)},trackVisit:function(){return y()},getForms:function(){B()},handleSubmit:function(a){J(a)},handleSubmitHS:function(a){C(a)},handleEmailFieldChange:function(a){e("m_handleEmailFieldChange");a=a.target.value;e("email: "+a);/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(a)?(window==window.top?F(a):parent.postMessage('{ "sender" : "fcdsc", "type": "setuppendingsave", "email" : "'+a+'"}',"*"),n(a)):
e("Invalid email")},setEmailFieldId:function(a){e("m_setEmailFieldId");a&&(M=a)},setNoRedirect:function(a){e("m_setNoRedirect");"boolean"==typeof a&&(W=a)},handleSubmitMkto:function(a,b){return S(a,b)},receiveMessage:function(a){e("m_receiveMessage");e("event.data: "+a.data);e("event.origin: "+a.origin);if("string"==typeof a.data)try{var b=JSON.parse(a.data);if(a.data.includes("pageId")){var f=a.data;e("m_handleSubmitUnbounce");var c=f.split("&");f=null;for(var g=0;g<c.length;g++){var k=c[g].split("=");
"pageId"==k[0].replace(/['"]+/g,"")&&(f=k[1])}if(f){var t=document.getElementsByName("pageId");if(t[0].value==f){var da=t[0].parentElement,aa=document.getElementById("email");if(!1===da.contains(aa))e("email element is not part of correct form");else if("input"!=aa.nodeName.toLowerCase())e("email element is not input, exiting");else{var d=aa.value;d?F(d):e("could not find email field/value")}}}}a.data.includes("mktoReady")&&b.mktoReady&&B();if(b.sender&&"fcdsc"===b.sender){var h=b.type.toLowerCase();
"trackformfill"===h&&n(b.email);"setuppendingsave"===h&&F(b.email);"setuppendingmultisave"===h&&P(b.email);"checkforpendingsave"===h&&I()}}catch(l){e("error in m_receiveMessage: "+l)}},checkForPendingSave:function(){I()},setupPendingSave:function(a){F(a)},setupPendingMultiSave:function(a){P(a)},trackFormFill:function(a){return n(a)},log:function(a){e(a)},addMutationObservers:function(a){E(a)},isDoNotTrackEnabled:function(){return q()},hasPrefilledEmail:function(){var a=H?!0:!1;return a},trackingOptIn:function(){e("m_trackingOptIn");
U=!1;A("_fcdscblock")&&v("_fcdscblock","",-1);fcdscLoad()},trackingOptOut:function(a){e("m_trackingOptOut");U=!0;m("_fcdscv")&&v("_fcdscv","",-1);m("_fcdsctmp")&&v("_fcdsctmp","",-1);m("_fcdscms")&&v("_fcdscms","",-1);A("_fcdscst")&&v("_fcdscst","",-1);a&&x("_fcdscblock","1")}}}();
function fcdscLoad(){fcdsc.init();if(fcdsc.isValidOrigin(window.location.hostname)){fcdsc.getForms();fcdsc.checkForPendingSave();fcdsc.addMutationObservers();window==window.top&&("undefined"!==typeof MktoForms2&&fcdsc.hasPrefilledEmail()&&MktoForms2.whenReady(function(n){n.onSuccess(fcdsc.handleSubmitMkto)}),window.addEventListener("message",fcdsc.receiveMessage,!1),window.addEventListener("hsvalidatedsubmit",fcdsc.handleSubmitHS,!1),fcdsc.isDoNotTrackEnabled()||fcdsc.trackVisit());var y=new CustomEvent("fcdscOnLoad");
window.dispatchEvent(y)}else console.log("FCDSC: not a valid origin, exiting")}window.addEventListener?window.addEventListener("load",fcdscLoad,!1):window.attachEvent&&window.attachEvent("onload",fcdscLoad);"undefined"!==typeof MktoForms2&&window==window.top&&MktoForms2.whenReady(fcdscLoad);String.prototype.startsWith||Object.defineProperty(String.prototype,"startsWith",{value:function(y,n){pos=0<n?n|0:0;return this.substring(pos,pos+y.length)===y}});
String.prototype.includes||(String.prototype.includes=function(y,n){"number"!==typeof n&&(n=0);return n+y.length>this.length?!1:-1!==this.indexOf(y,n)});"".trim||(String.prototype.trim=function(){return this.replace(/^[\s\ufeff]+|[\s\ufeff]+$/g,"")});
(function(y){y.DOMException||((DOMException=function(r){this.message=r}).prototype=Error());var n=/[\11\12\14\15\40]/,Q=0,V=function(r,D){if(""===D)throw new DOMException("Failed to execute '"+r+"' on 'DOMTokenList': The token provided must not be empty.");if(-1!==(Q=D.search(n)))throw new DOMException("Failed to execute '"+r+"' on 'DOMTokenList': The token provided ('"+D[Q]+"') contains HTML space characters, which are not valid in tokens.");};"function"!==typeof DOMTokenList&&function(r){function D(){if(!X)throw TypeError("Illegal constructor");
}function u(){var m=r.event,A=m.propertyName;if(!L&&("className"===A||"classList"===A&&!O)){m=m.srcElement;var v=m[" uCLp"],x=""+m[A],q=x.trim().split(n),B=m["classList"===A?" uCL":"classList"],J=v.length,C=0,I=v.length=q.length;v=0;a:for(;C!==I;++C){for(var F=0;F!==C;++F)if(q[F]===q[C]){v++;continue a}B[C-v]=q[C]}for(C=I-v;C<J;++C)delete B[C];"classList"===A&&(L=1,m.classList=B,m.className=x,L=0,B.length=q.length-v)}}function e(m){if(!(m&&"innerHTML"in m))throw TypeError("Illegal invocation");m.detachEvent("onpropertychange",
u);X=1;try{(function(){}).prototype=new D}finally{X=0}var A=protoObj.prototype,v=new protoObj,x=m.className.trim().split(n),q=0,B=x.length,J=0;a:for(;q!==B;++q){for(var C=0;C!==q;++C)if(x[C]===x[q]){J++;continue a}this[q-J]=x[q]}A.length=B-J;A.value=m.className;A[" uCL"]=m;O?(O(m,"classList",{enumerable:1,get:function(){return v},configurable:0,set:function(I){L=1;m.className=A.value=I+="";L=0;var F=I.trim().split(n);I=A.length;var P=0,S=A.length=F.length,E=0;a:for(;P!==S;++P){for(var T=0;T!==P;++T)if(F[T]===
F[P]){E++;continue a}v[P-E]=F[P]}for(F=S-E;F<I;++F)delete v[F]}}),O(m," uCLp",{enumerable:0,configurable:0,writeable:0,value:protoObj.prototype}),O(A," uCL",{enumerable:0,configurable:0,writeable:0,value:m})):(m.classList=v,m[" uCL"]=v,m[" uCLp"]=protoObj.prototype);m.attachEvent("onpropertychange",u)}var G=r.document,N=r.Object,Z=N.prototype.hasOwnProperty,O=N.defineProperty,X=0,L=0;D.prototype.toString=D.prototype.toLocaleString=function(){return this.value};D.prototype.add=function(){var m=0,A=
arguments.length,v=this[" uCL"],x=v[" uCLp"];a:for(;m!==A;++m){var q=arguments[m]+"";V("add",q);for(var B=0,J=x.length,C=q;B!==J;++B)if(this[B]===q)continue a;else C+=" "+this[B];this[J]=q;x.length+=1;x.value=C}L=1;v.className=x.value;L=0};D.prototype.remove=function(){for(var m=0,A=arguments.length,v,x=this[" uCL"],q=x[" uCLp"];m!==A;++m){v=arguments[m]+"";V("remove",v);for(var B=0,J=q.length,C="",I=0;B!==J;++B)I?this[B-1]=this[B]:this[B]!==v?C+=this[B]+" ":I=1;I&&(delete this[J],--q.length,q.value=
C)}L=1;x.className=q.value;L=0};r.DOMTokenList=D;try{r.Object.defineProperty(r.Element.prototype,"classList",{enumerable:1,get:function(m){Z.call(this,"classList")||e(this);return this.classList},configurable:0,set:function(m){this.className=m}})}catch(m){r[" uCL"]=e,G.documentElement.firstChild.appendChild(G.createElement("style")).styleSheet.cssText='_*{x-uCLp:expression(!this.hasOwnProperty("classList")&&window[" uCL"](this))}[class]{x-uCLp/**/:expression(!this.hasOwnProperty("classList")&&window[" uCL"](this))}'}}(y);
(function(r,D){r.item||(r.item=function(u){u=this[u];return void 0===u?null:u});r.toggle&&!1===D.toggle("a",0)||(r.toggle=function(u){if(1<arguments.length)return this[arguments[1]?"add":"remove"](u),!!arguments[1];var e=this.value;return this.remove(e),e===this.value&&(this.add(u),!0)});r.replace&&"boolean"===typeof D.replace("a","b")||(r.replace=function(u,e){V("replace",u);V("replace",e);var G=this.value;return this.remove(u),this.value!==G&&(this.add(e),!0)});r.contains||(r.contains=function(u){for(var e=
0,G=this.length;e!==G;++e)if(this[e]===u)return!0;return!1});r.forEach||(r.forEach=function(u){if(1===arguments.length)for(var e=0,G=this.length;e!==G;++e)u(this[e],e,this);else{e=0;G=this.length;for(var N=arguments[1];e!==G;++e)u.call(N,this[e],e,this)}});r.entries||(r.entries=function(){var u=0,e=this;return{next:function(){return u<e.length?{value:[u,e[u++]],done:!1}:{done:!0}}}});r.values||(r.values=function(){var u=0,e=this;return{next:function(){return u<e.length?{value:e[u++],done:!1}:{done:!0}}}});
r.keys||(r.keys=function(){var u=0,e=this;return{next:function(){return u<e.length?{value:u++,done:!1}:{done:!0}}}})})(y.DOMTokenList.prototype,y.document.createElement("div").classList)})(window);(function(){if("function"===typeof window.CustomEvent)return!1;window.CustomEvent=function(y,n){n=n||{bubbles:!1,cancelable:!1,detail:null};var Q=document.createEvent("CustomEvent");Q.initCustomEvent(y,n.bubbles,n.cancelable,n.detail);return Q}})();fcdscLoad();